// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfflineChallenge;

#nullable disable

namespace OfflineChallenge.Migrations
{
    [DbContext(typeof(CountryCovidInfoDbContext))]
    partial class CountryCovidInfoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("OfflineChallenge.CountryCovidInfo", b =>
                {
                    b.Property<int>("CountryCovidInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActiveCases")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("TotalCases")
                        .HasColumnType("TEXT");

                    b.Property<string>("TotalTests")
                        .HasColumnType("TEXT");

                    b.HasKey("CountryCovidInfoId");

                    b.ToTable("CountryCovidInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
